/* eslint-disable @next/next/no-img-element */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navBar";
import Providers from "./providers";
import { Suspense } from "react";
import Loading from "@/components/loader";
import { getCartItems } from "./actions";
import Modal from "@/components/modal";
import CartContent from "@/components/cartContent";
import { cn } from "@/lib/utils";
import Sidebar from "@/components/sidebar";
import { Card, CardContent } from "@/components/ui/card";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Next13 Crash Course",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
  // productList: React.ReactNode;
}) {
  //const productData = prisma.product.findMany();
  const cart = await getCartItems();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen w-full bg-cover bg-no-repeat bg-[url('/road.jpg')] bg-slate-500 bg-blend-overlay",
          inter.variable
        )}
      >
        <NavBar />

        {/* <Providers> */}

        <Sidebar />
        <div className=" ml-[275px] pr-10">
          <Card className="min-h-fit mb-5 rounded-2xl border-none bg-gray-300 bg-opacity-90 h-[600px]">
            <CardContent className=" px-0 py-2">{children}</CardContent>
          </Card>
        </div>
        {/* </Providers> */}
        {/* <Modal>
          <CartContent />
        </Modal> */}
      </body>
    </html>
  );
}
